// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthx_qfHbs0rA3cVh1KE4XvxpBxWy4FxM',
    appId: '1:778533267781:web:8945eea78f3be8e8f9f62c',
    messagingSenderId: '778533267781',
    projectId: 'autoinsight-2b981',
    authDomain: 'autoinsight-2b981.firebaseapp.com',
    storageBucket: 'autoinsight-2b981.appspot.com',
    measurementId: 'G-M1X4M2HTH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8-1304JIa5_1wnLBuCVRGnBvrUJDhoo8',
    appId: '1:778533267781:android:a754b2296a203290f9f62c',
    messagingSenderId: '778533267781',
    projectId: 'autoinsight-2b981',
    storageBucket: 'autoinsight-2b981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdvxjgyGbTyO3HyjFZsOojYqzRrBg6uGo',
    appId: '1:778533267781:ios:b781e68ab6288760f9f62c',
    messagingSenderId: '778533267781',
    projectId: 'autoinsight-2b981',
    storageBucket: 'autoinsight-2b981.appspot.com',
    iosClientId: '778533267781-81uhka6vc4v67vdh0cvd6l554uqnt0iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoinsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdvxjgyGbTyO3HyjFZsOojYqzRrBg6uGo',
    appId: '1:778533267781:ios:b781e68ab6288760f9f62c',
    messagingSenderId: '778533267781',
    projectId: 'autoinsight-2b981',
    storageBucket: 'autoinsight-2b981.appspot.com',
    iosClientId: '778533267781-81uhka6vc4v67vdh0cvd6l554uqnt0iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoinsight',
  );
}
